### ISSUE TITLE
ncvis when gcc libraries not in paths workarounds

### ISSUE THREAD

**Issue by zarzycki** [SEATStandards/ncvis#15]
More a potential workaround than an issue...

In INSTALL.md, currently there are "Cheyenne-specific" instructions.

Even after a successful compile, a potential headache arises if one's default compiler is not gnu (for example, I prefer the intel set). Running `ncvis` from the command line requires loading the gcc module which could break workflows (and also require users to remember to flip the modules back). This needs to be done every time `ncvis` is invoked since it is looking for gcc libraries.

If you successfully compile but then try to run the binary in another session (say one where intel compilers are in the path), you can get the following error:

```
(base) zarzycki@cheyenne5:/glade/work/zarzycki/sewx/INIC> ~/sw/ncvis/ncvis RAP_2012063006.nc 
/glade/u/home/zarzycki/sw/ncvis/ncvis: /glade/u/apps/ch/os/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /glade/u/home/zarzycki/sw/ncvis/ncvis)
```

However, the issue can be alleviated by passing the library path in as a "one-off" when invoking the binary.

```
LD_LIBRARY_PATH=/glade/u/apps/ch/opt/gnu/12.1.0/lib64 ~/sw/ncvis/ncvis RAP_2012063006.nc 
```

I have it mapped to an alias:

```
alias ncvis="LD_LIBRARY_PATH=/glade/u/apps/ch/opt/gnu/12.1.0/lib64 /glade/u/home/zarzycki/sw/ncvis/ncvis"
```

Now I don't touch the module environment but invoke `ncvis` as I would `ncview`.

```
(base) zarzycki@cheyenne5:/glade/work/zarzycki/sewx/INIC> ncvis RAP_2012063006.nc 
NcVis 2022.08.31 Paul A. Ullrich
Generating quadtree from lat/lon arrays
..0% complete
..1% complete
```

**Comment by rljacob** [comment]
Hi @zarzycki .  I run in to this a lot on machines with multiple compilers.  Your workaround is a good one.  If you're trying to make the binary available to all users, what I do is change it's name to ncvis.exe and create a script called "ncvis" which loads the library and calls ncvis.exe.

Did you try compiling ncvis with intel and it didn't work?

**Comment by taobrienlbl** [comment]
I love that solution: will definitely use in other places!

**Comment by paullric** [comment]
Seems like we should add the path explicitly during linking:  "-Wl,-rpath=/glade/u/apps/ch/opt/gnu/12.1.0/lib64"  I can't test it right now since Cheyenne is down but will have a look later.

**Comment by taobrienlbl** [comment]
@rljacob - I think I was the one who originally ported this to cheyenne, and if I recall correctly, I wasn't able to compile with intel right off the bat.  That said, I didn't invest much time in it, since I got it to compile pretty quickly with gnu.
