### ISSUE TITLE
Adding ncvis as ncvis-climate to conda-forge

### ISSUE THREAD

**Issue by mahf708** [SEATStandards/ncvis#16]
xref https://github.com/conda-forge/staged-recipes/pull/23033

Currently, it seems it builds correctly, but running into linking errors that have been discussed in the repo here.

- Is the name `ncvis-climate` okay? There is already `ncvis` in conda-forge
- Please have a look at the conda-forge recipe, and let me know if you can help fix the linking issues. I also am more than happy to add whomever is interested to the list of maintainers

**Comment by rljacob** [comment]
cc: @rajeeja

**Comment by taobrienlbl** [comment]
@mahf708 - this would be wonderful!  I just installed on perlmutter and got the following error that suggests some fonts might need to be added to the package:

```
$ ncvis e5.oper.an.vinteg.162_089_vilwn.ll025sc.2020030100_2020033123.nc
./src/common/filename.cpp(2027): assert ""Assert failure"" failed in IsValidDirComponent(): invalid directory component in wxFileName
NcVis 2022.08.28 Paul A. Ullrich
ERROR: Font "/global/common/software/m1517/perlmutter/climatetools/bin/Ubuntu-Regular.ttf" not found
```

**Comment by taobrienlbl** [comment]
conda reports that it's not available in that channel

**Comment by taobrienlbl** [comment]
sorry, should have said that I tried that too - doesn't seem to be visible yet to me on conda-forge

**Comment by taobrienlbl** [comment]
oh, it's using the package cache .. hang on, let me figure out how to override that

**Comment by taobrienlbl** [comment]
not a problem at all.  Unfortunately just ran out of time for the day - need to head out.  I'll pick this back up on Monday (maybe tomorrow)

**Comment by rljacob** [comment]
@mahf708 Q about how the conda forge version gets update?  Does someone have to do something or does it pull the latest (tag? main?) from here?
