### ISSUE TITLE
QOL improvements? colormap inversion + zoom out support

### ISSUE THREAD

**Issue by zarzycki** [SEATStandards/ncvis#17]
1.) Allow inversion of colormaps as in ncview. Beneficial when you prefer a colormap but the relative scaling of the variable is inverted. An example of this is FLUT and the gray colormap -- for satellite images, lower OLR (brightness T) is generally colored white. but the current scaling sets white as the maximum of the range. This should be pretty easy in GenerateColorMap (something like std::reverse?).

2.) Double clicking allows zooming in, is there a way to allow zooming out? ncview has the ability to pan, although I generally find that far less useful than zoom out/recenter. This doesn't necessarily need to be a mouse/keyboard shortcut -- I assume a double click on zoom in "locks" a central ncol, that value can just be re-used with a zoom out button in the GUI (i.e., zoom out centered on the most recent "zoom in centroid?")

If I'm missing something, maybe making it more obvious would be helpful (for me... I mean, "other users" :)

**Comment by paullric** [comment]
Color map invert button added in commit 077d5ac
