### ISSUE TITLE
[Feature Request] Add variable name to top of plot

### ISSUE THREAD

**Issue by whannah1** [SEATStandards/ncvis#5]
The export feature is nice… but when I share ncview images on slack I rely on a quick screen shot (i.e. cmd+opt+shift+4 on Mac). This is mainly because I’m opening ncview on a remote machine via x11, so I don’t want to export and then transfer a file, I just want to put what I’m looking at in the clipboard and paste it immediately into slack as quickly as possible. Having a variable name  shown at the top of the plot (and perhaps the vertical level, regional lat/lon bounds, or any sort of subset information) would really help when sharing images.

**Comment by paullric** [comment]
Variable name (and long_name) now displayed in NcVis 2022.08.25 commit 8fdff92cfbef0b3aa77e0bd28bb6793dadd7d68

<img width="842" alt="Screen Shot 2022-08-26 at 7 11 36 PM" src="https://user-images.githubusercontent.com/5330916/187010223-b3153675-c90d-4f9a-b1f2-ba9ebae3c6f1.png">
1

**Comment by paullric** [comment]
Major tickmarks and tickmark labels now added in NcVis 2022.08.28 commit b0c29601d0a5392669e4a0739ed20454de4f6a46

<img width="922" alt="Screen Shot 2022-08-28 at 6 23 55 PM" src="https://user-images.githubusercontent.com/5330916/187105052-e840557e-877f-4a69-9f93-294981ddfb01.png">

**Comment by whannah1** [comment]
Excellent, thanks!
