### ISSUE TITLE
[Feature Request] config file to identify grids

### ISSUE THREAD

**Issue by jedwards4b** [SEATStandards/ncvis#8]
In email from Paul: At present I make the assumption that (a) each file only has one longitude/latitude   variable, (b) the longitude/latitude variable is 1D, and (c) there is only one dimension name that refers to an unstructured dimension (normally ncol).

Can you add a config file in which the user could identify the grid dimensions used and explicitly identify the unstructured grid.

**Comment by mvertens** [comment]
@jedwards4b - thanks for suggesting this. That would solve the problem for the mediator history files in CESM.

**Comment by paullric** [comment]
Commit 8981794b9948c1170a5216939e8afbe4c99ccc30 now checks for variables with standard_name "latitude" and "longitude" that have the same dimensionality as the variable being displayed.  If detected then the GridDataSampler will be re-initialized when the variable is displayed.  This relaxes all three conditions above and allows the mediator files to be displayed without the need for a config file.
